name: Deploy to Railway
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.16.0
          
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --json --service FSW-Mock-Test

      - name: Setup database
        run: railway run --service FSW-Mock-Test npx prisma migrate deploy

      - name: URL
        id: url
        run: |
          {
            echo 'JSON_RESULT<<EOF'
            railway variables --json --service FSW-Mock-Test
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Print URL
        run: echo '[link to service](https://${{ fromJson(steps.url.outputs.JSON_RESULT).RAILWAY_PUBLIC_DOMAIN }}/api-docs)' >> $GITHUB_STEP_SUMMARY